# Generated by Django 4.2 on 2026-02-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="emails_emai_recipie_b52833_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailmessage",
            name="emails_emai_sender__c70715_idx",
        ),
    ]
