# Generated by Django 4.2 on 2026-02-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_remove_emailmessage_emails_emai_recipie_b52833_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailmessage",
            name="is_deleted",
        ),
    ]
