# Generated by Django 4.2 on 2026-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdevice",
            options={
                "ordering": ["-last_login"],
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.AddField(
            model_name="userdevice",
            name="read_permission",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="write_permission",
            field=models.BooleanField(default=False),
        ),
    ]
