# Generated by Django 4.2 on 2026-02-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_userdevice_options_userdevice_read_permission_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdevice",
            options={"ordering": ["-last_login"]},
        ),
    ]
